package repository

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Job is a job type definition
// it is used for response and internal queueing
type Job struct {
	ID      primitive.ObjectID `bson:"_id" json:"id"`
	Message string             `bson:"message" json:"message,omitempty"` // message to check

	Finished  bool      `bson:"finished" json:"successful"`     // was done
	LastTried time.Time `bson:"lastTried" json:"lastTry"`       // used for sorting
	Result    string    `bson:"result" json:"result,omitempty"` // result to return
}

// EmptyResponseError marks an error that 0 item from DB were returned
type EmptyResponseError struct{}

// Error returns string representation of error
func (r EmptyResponseError) Error() string {
	return "no response from DB"
}

// NewJob returns new Job struct, with autogenerated ID - useful for testing
func NewJob() Job {
	return Job{
		ID: primitive.NewObjectID(),
	}
}

// Repository is an interface definition for database related methods
type Repository interface {
	GetJobByIdCtx(context.Context, primitive.ObjectID) (*Job, error)
	GetUnfinishedJobsCtx(context.Context) (*Job, error)
	InsertJobCtx(context.Context, *Job) (*primitive.ObjectID, error)
	UpdateJobCtx(context.Context, *Job) error
}
